total_iters: 166250
output_dir: /root/paddlejob/workspace/output
# tensor range for function tensor2img
min_max: 
  (0., 255.)

model:
  name: RCANModel
  generator:
    name: RCAN
    scale: 4
    n_resgroups: 10
    n_resblocks: 20
  pixel_criterion:
    name: L1Loss

dataset:
  train:
    name: SRDataset
    gt_folder: ./data/PMBA/data_all_HR_x4
    lq_folder: ./data/PMBA/data_all_LR_x4
    num_workers: 4
    batch_size: 16
    scale: 4
    preprocess:
      - name: LoadImageFromFile
        key: lq
      - name: LoadImageFromFile
        key: gt
      - name: Transforms
        input_keys: [lq, gt]
        pipeline:
          - name: SRPairedRandomCrop
            gt_patch_size: 192
            scale: 4
            keys: [image, image]
          - name: PairedRandomHorizontalFlip
            keys: [image, image]
          - name: PairedRandomVerticalFlip
            keys: [image, image]
          - name: PairedRandomTransposeHW
            keys: [image, image]
          - name: Transpose
            keys: [image, image]
          - name: Normalize
            mean: [0., .0, 0.]
            std: [1., 1., 1.]
            keys: [image, image]
  test:
    name: SRDataset
    gt_folder: ./data/PMBA/test_HR
    lq_folder: ./data/PMBA/test_LR_x4
    scale: 4
    preprocess: 
      - name: LoadImageFromFile
        key: lq
      - name: LoadImageFromFile
        key: gt
      - name: Transforms
        input_keys: [lq, gt]
        pipeline:
          - name: Transpose
            keys: [image, image]
          - name: Normalize
            mean: [0., .0, 0.]
            std: [1., 1., 1.]
            keys: [image, image]

lr_scheduler:
  name: CosineAnnealingRestartLR
  learning_rate: 0.0001
  periods: [166250]
  restart_weights: [1]
  eta_min: !!float 1e-7

optimizer:
  name: Adam
  # add parameters of net_name to optim
  # name should in self.nets
  net_names:
    - generator
  beta1: 0.9
  beta2: 0.99

validate:
  interval: 1000
  save_img: false

  metrics:
    psnr: # metric name, can be arbitrary
      name: PSNR
      crop_border: 4
      test_y_channel: True
    ssim:
      name: SSIM
      crop_border: 4
      test_y_channel: True
    rmse:
      name: RMSE
      crop_border: 4
    mad:
      name: MAD
      crop_border: 4
    pe:
      name: PE
      crop_border: 4

log_config:
  interval: 100
  visiual_interval: 500

snapshot_config:
  interval: 5000